### ISSUE TITLE
Error on summary: "Calling method 'end_suite' of listener 'RobotNotifications' failed"

### ISSUE THREAD

**Issue by paolofulgoni** [tlolkema/RobotNotifications#3]
After an upgrade to RobotFramework 4.0.3, the RobotNotification listener rises this error, when the `summary` argument is passed:

`[ ERROR ] Calling method 'end_suite' of listener 'RobotNotifications' failed: AttributeError: 'TotalStatistics' object has no attribute 'all'`

It was working fine with RobotFramework 3.1.2.

I've just checked the [result.statistics](https://robot-framework.readthedocs.io/en/master/autodoc/robot.result.html#robot.result.model.TestSuite.statistics), and the [TotalStatistics](https://robot-framework.readthedocs.io/en/master/autodoc/robot.model.html#robot.model.totalstatistics.TotalStatistics) class doesn't actually have an `all` property.

Should these lines be changed removing `.all` (e.g. `result.statistics.total`)?
https://github.com/tlolkema/RobotNotifications/blob/cc1edc10fa2be88d1bac50be0382008d016d6785/RobotNotifications/__init__.py#L86-L92

Thanks!

**Comment by tlolkema** [comment]
Thanks for mentioning this issue, if will let you know when it's fixed

**Comment by tlolkema** [comment]
@paolofulgoni I released a new version 1.2.0 of robotframework-notifications which should fix the issue. 

Can you check again? 

Fix is backwards compatible so this package will still work with older versions of robotframework.

**Comment by paolofulgoni** [comment]
Hi @tlolkema, thanks a lot for the quick fix!
I confirm that the issue is fixed 🙌
